package kit

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const csproj = `<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <ItemGroup>
    <Compile Include="..\Forms\MainForm.cs" />
    <Compile Include="..\forms\mainform.designer.cs" />
    <Compile Include="..\Dx\Grid%2Ecs" />
    <Compile Include="Missing.cs" />
    <Compile Include="..\..\outside.cs" />
    <Compile Include="C%3A\x.cs" />
    <Compile Include="\\server\share\x.cs" />
    <Compile Include="**\*.cs" />
    <Compile Include="$(Gen)\x.cs" />
    <Compile Include="..\Bin\Debug\x.cs" />
    <Reference Include="System.Data" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <Compile Include="..\Svc\IService.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\App.config;..\Schema\a.xsd" />
    <Compile Include="..\Dx\Grid.cs" Exclude="..\Dx\Grid.cs" />
  </ItemGroup>
  <Choose>
    <When Condition="'$(X)'=='1'"><ItemGroup><Compile Include="..\Misc\gen.cs" /></ItemGroup></When>
    <Otherwise><ItemGroup><Compile Include="..\Misc\u16.cs" /></ItemGroup></Otherwise>
  </Choose>
  <Target Name="Gen"><ItemGroup><Compile Include="..\dup1\a.cs" /></ItemGroup></Target>
</Project>
`

var corpusFixture = map[string]string{
	"Forms/MainForm.cs":                "partial class MainForm : Form { void X() { InitializeComponent(); } }\r\n",
	"Forms/MainForm.Designer.cs":       "partial class MainForm { System.ComponentModel.ComponentResourceManager r; }\n",
	"Properties/Resources.Designer.cs": "// <auto-generated>\nglobal::System.Resources.ResourceManager x;\n",
	"Properties/Resources.resx":        "<root/>\n",
	"Svc/Service1.svc":                 `<%@ ServiceHost Service="X" %>`,
	"Svc/Service1.svc.cs":              "class S {}\n",
	"Svc/IService.cs":                  "[ServiceContract] interface I {}\n",
	"Ref/Reference.cs":                 "class P : ClientBase<I> {}\n",
	"Dx/Grid.cs":                       "var g = new DevExpress.XtraGrid.GridControl();\n",
	"App.config":                       "<configuration/>\r\n",
	"Schema/a.xsd":                     "<xs:schema/>\n",
	"Data/q.sql":                       "\xc7\xd1\r",
	"Misc/notes.txt":                   "x\n",
	"Misc/data.xml":                    "<a/>\n\r\n",
	"Misc/u16.cs":                      "\xff\xfea\x00\r\x00\n\x00",
	"Misc/gen.cs":                      "// <auto-generated/>\nclass G {}\n",
	"Keys/sign.PFX":                    "SECRET-NEVER-READ",
	"Lib/vendor.dll":                   "MZ",
	"Bin/Debug/x.cs":                   "excluded",
	"obj/y.cs":                         "excluded",
	".git/config":                      "excluded",
	"packages/p/z.cs":                  "excluded",
	"TestResults/r.xml":                "excluded",
	"dup1/a.cs":                        "same\n",
	"dup2/a.cs":                        "same\n",
	"App/App.csproj":                   csproj,
}

func corpusRun(t *testing.T, root string, l CorpusLimits) (CorpusResult, error) {
	t.Helper()
	return Corpus(testCtx(t), CorpusRequest{Root: root, Limits: l, Encoding: EncodingPolicy{Profile: "cp949"}})
}

// S01-A18: roles, PRESENCE_ONLY, exclusions, .csproj membership and per-file observations.
func TestCorpusInventory(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, corpusFixture)
	var opened []string
	testHookOpen = func(name string) { opened = append(opened, name) }
	t.Cleanup(func() { testHookOpen = nil })
	res, err := corpusRun(t, root, DefaultCorpusLimits())
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range opened {
		if strings.EqualFold(filepath.Ext(name), ".pfx") || strings.HasSuffix(name, ".dll") {
			t.Fatalf("PRESENCE_ONLY content opened: %s", name)
		}
	}
	recs := map[string]CorpusRecord{}
	for _, r := range res.Records {
		recs[r.Path] = r
		if strings.HasPrefix(strings.ToLower(r.Path), "bin/") || strings.HasPrefix(r.Path, "obj/") || strings.HasPrefix(r.Path, ".git/") || strings.HasPrefix(r.Path, "packages/") || strings.HasPrefix(r.Path, "TestResults/") {
			t.Fatalf("excluded directory recorded: %s", r.Path)
		}
	}
	if res.Summary.ExcludedDirs != 5 || len(res.Records) != 21 || res.Summary.Files != 21 {
		t.Fatalf("counts: excluded %d records %d", res.Summary.ExcludedDirs, len(res.Records))
	}
	wantRole := map[string]string{
		"Forms/MainForm.cs": "N461-FORM", "Forms/MainForm.Designer.cs": "N461-FORM", "Properties/Resources.Designer.cs": "N461-RESOURCE",
		"Properties/Resources.resx": "N461-RESOURCE", "Svc/Service1.svc": "N461-SVC", "Svc/Service1.svc.cs": "N461-WCF-CS", "Svc/IService.cs": "N461-WCF-CS",
		"Ref/Reference.cs": "N461-WCF-CS", "Dx/Grid.cs": "N461-DX202", "App.config": "N461-XML", "Schema/a.xsd": "N461-XML",
		"Data/q.sql": RoleUnclassified, "Misc/notes.txt": RoleUnclassified, "Misc/data.xml": RoleUnclassified, "Keys/sign.PFX": RoleUnclassified, "App/App.csproj": RoleUnclassified,
	}
	for p, role := range wantRole {
		if recs[p].Role != role {
			t.Errorf("%s role %s, want %s", p, recs[p].Role, role)
		}
	}
	wantRoute := map[string]string{"Data/q.sql": "tsql", "Svc/Service1.svc": "svc", "Misc/data.xml": "xml", "Properties/Resources.resx": "xml", "Misc/notes.txt": "", "Forms/MainForm.Designer.cs": "csharp", "App/App.csproj": "", "Lib/vendor.dll": ""}
	for p, route := range wantRoute {
		if recs[p].Route != route {
			t.Errorf("%s route %q, want %q", p, recs[p].Route, route)
		}
	}
	for _, p := range []string{"Keys/sign.PFX", "Lib/vendor.dll"} {
		r := recs[p]
		if r.State != RecordPresenceOnly || r.SHA256 != "" || r.Encoding != nil || r.Size != uint64(len(corpusFixture[p])) {
			t.Fatalf("presence-only record %+v", r)
		}
	}
	if q := recs["Data/q.sql"]; q.Encoding.Assessment != "PASS" || q.Encoding.Encoding != EncodingCP949 || q.Newline != "CR" {
		t.Fatalf("cp949 record %+v %+v", q, q.Encoding)
	}
	if u := recs["Misc/u16.cs"]; u.Encoding.Encoding != EncodingUTF16LE || u.Newline != "CRLF" {
		t.Fatalf("UTF-16 newline %+v", u)
	}
	for p, nl := range map[string]string{"Forms/MainForm.cs": "CRLF", "Svc/Service1.svc": "NONE", "Misc/data.xml": "MIXED", "Misc/notes.txt": "LF"} {
		if recs[p].Newline != nl {
			t.Errorf("%s newline %s want %s", p, recs[p].Newline, nl)
		}
	}
	for p, basis := range map[string]string{"Forms/MainForm.Designer.cs": "NAME", "Ref/Reference.cs": "NAME", "Misc/gen.cs": "MARKER"} {
		if !recs[p].Generated || recs[p].GeneratedBasis != basis {
			t.Errorf("%s generated %+v", p, recs[p])
		}
	}
	if recs["Dx/Grid.cs"].Generated || recs["dup1/a.cs"].DuplicateCount != 2 || res.Summary.DuplicateGroups != 1 || res.Summary.RedundantCopies != 1 {
		t.Fatalf("duplicates/generated: %+v", res.Summary)
	}
	if len(res.Projects) != 1 {
		t.Fatalf("projects %+v", res.Projects)
	}
	proj := res.Projects[0]
	states := map[string]int{}
	for _, it := range proj.Items {
		states[it.State]++
	}
	if proj.State != "PARSED" || proj.Imports != 1 || proj.IgnoredItems != 1 || states["MEMBER"] != 5 || states["NOT_FOUND"] != 4 || states["UNRESOLVED"] != 7 || states["EXCLUDED"] != 1 {
		t.Fatalf("project observation %+v %v", proj, states)
	}
	if got := recs["Forms/MainForm.Designer.cs"].DeclaredBy; len(got) != 1 || got[0] != "App/App.csproj" {
		t.Fatalf("case-insensitive membership: %v", got)
	}
	for _, p := range []string{"Svc/IService.cs", "Misc/gen.cs", "Misc/u16.cs", "dup1/a.cs"} {
		if len(recs[p].DeclaredBy) != 0 {
			t.Fatalf("conditional, Choose, Exclude or Target item must stay UNRESOLVED: %s", p)
		}
	}
	if res.ExecutionStatus != StatusCompleted || res.Assessment != AssessNotAssessed || res.Summary.PresenceOnly["credential"] != 1 || res.Summary.PresenceOnly["vendor_binary"] != 1 {
		t.Fatalf("summary %+v", res.Summary)
	}
}

// S01-A19: each private-corpus-local limit at the boundary and one over.
func TestCorpusLimits(t *testing.T) {
	if d := DefaultCorpusLimits(); d != (CorpusLimits{Files: 26000, Records: 26000, FileBytes: 33554432, TotalBytes: 3489660928, Depth: 32, ReportBytes: 67108864, Wall: 1800 * time.Second}) {
		t.Fatalf("registered limits changed: %+v", d)
	}
	root := t.TempDir()
	writeTree(t, root, map[string]string{"a.cs": "abc", "b.cs": "de", "d1/d2/c.cs": "f", "k.pem": strings.Repeat("k", 100)})
	at := DefaultCorpusLimits()
	at.Files, at.Records, at.FileBytes, at.TotalBytes, at.Depth = 4, 4, 3, 6, 3
	res, err := corpusRun(t, root, at)
	if err != nil || res.Summary.BytesRead != 6 || res.Summary.Files != 4 {
		t.Fatalf("at limits: %v %+v", err, res.Summary)
	}
	for i := 0; i < 8; i++ {
		at.ReportBytes = uint64(len(mustJSON(t, res))) + 1
		if res, err = corpusRun(t, root, at); err != nil {
			t.Fatalf("report at limit: %v", err)
		}
	}
	for _, tc := range []struct {
		code   string
		mutate func(*CorpusLimits)
	}{
		{"FILE_COUNT_LIMIT", func(l *CorpusLimits) { l.Files = 3 }},
		{"RECORD_LIMIT", func(l *CorpusLimits) { l.Records = 3 }},
		{"TOTAL_BYTES_LIMIT", func(l *CorpusLimits) { l.TotalBytes = 5 }},
		{"DEPTH_LIMIT", func(l *CorpusLimits) { l.Depth = 2 }},
		{"OUTPUT_LIMIT", func(l *CorpusLimits) { l.ReportBytes-- }},
		{"WALL_LIMIT", func(l *CorpusLimits) { l.Wall = time.Nanosecond }},
	} {
		t.Run(tc.code, func(t *testing.T) {
			l := at
			tc.mutate(&l)
			if tc.code == "WALL_LIMIT" {
				defer wallExpiringAtOpen(t)()
			}
			res, err := corpusRun(t, root, l)
			kindOf(t, err, KindResourceLimit, tc.code)
			if res.ExecutionStatus != StatusResourceLimit || res.Assessment != AssessBlocked || len(res.Records) != 0 {
				t.Fatalf("partial corpus result: %+v", res.Report)
			}
		})
	}
	t.Run("caller-cancel-wins-over-wall", func(t *testing.T) {
		// the caller's cancellation stays CANCELLED even when the kit wall has also expired
		defer wallExpiringAtOpen(t)()
		ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
		cancel()
		_, err := Corpus(ctx, CorpusRequest{Root: root, Limits: at, Encoding: EncodingPolicy{Profile: "cp949"}})
		kindOf(t, err, KindCancelled, "CANCELLED")
	})
	t.Run("per-file-limit-is-record-scoped", func(t *testing.T) {
		l := at
		l.FileBytes = 2
		var opened []string
		testHookOpen = func(name string) { opened = append(opened, name) }
		defer func() { testHookOpen = nil }()
		res, err := corpusRun(t, root, l)
		if err != nil || res.ExecutionStatus != StatusCompleted {
			t.Fatal(err)
		}
		for _, r := range res.Records {
			if r.Path == "a.cs" && (r.State != RecordResourceLimit || r.SHA256 != "") {
				t.Fatalf("over-limit record %+v", r)
			}
			if r.Path == "k.pem" && r.State != RecordPresenceOnly {
				t.Fatalf("PRESENCE_ONLY is exempt from the per-file limit: %+v", r)
			}
		}
		for _, name := range opened {
			if name == "a.cs" || name == "k.pem" {
				t.Fatalf("%s read", name)
			}
		}
	})
	t.Run("file-over-32MiB", func(t *testing.T) {
		big := t.TempDir()
		f, err := os.Create(filepath.Join(big, "huge.cs"))
		if err != nil {
			t.Fatal(err)
		}
		if err := f.Truncate(33554432 + 1); err != nil {
			t.Fatal(err)
		}
		f.Close()
		writeTree(t, big, map[string]string{"at.cs": "x"})
		res, err := corpusRun(t, big, DefaultCorpusLimits())
		if err != nil || res.Records[1].Path != "huge.cs" || res.Records[1].State != RecordResourceLimit || res.Records[1].SizeClass != "OVER_32MIB" || res.Summary.BytesRead != 1 {
			t.Fatalf("over 32 MiB: %v %+v", err, res.Records)
		}
	})
	t.Run("caller-cancel-is-cancelled", func(t *testing.T) {
		ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
		cancel()
		_, err := Corpus(ctx, CorpusRequest{Root: root, Limits: at})
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("caller cancel: %v", err)
		}
		kindOf(t, err, KindCancelled, "CANCELLED")
	})
	t.Run("declaration-applies-exact-path", func(t *testing.T) {
		res, err := Corpus(testCtx(t), CorpusRequest{Root: root, Limits: DefaultCorpusLimits(), Encoding: EncodingPolicy{Profile: "cp949", Files: []FileEncoding{{"b.cs", "utf-8"}}}})
		if err != nil {
			t.Fatal(err)
		}
		for _, r := range res.Records {
			if r.Path == "b.cs" && (r.Encoding == nil || r.Encoding.Source != SourceDeclaration) {
				t.Fatalf("declaration not applied: %+v", r.Encoding)
			}
		}
		_, err = Corpus(testCtx(t), CorpusRequest{Root: root, Limits: at, Encoding: EncodingPolicy{Files: []FileEncoding{{"B.cs", "utf-8"}}}})
		kindOf(t, err, KindInvalidInput, "DECLARATION_UNMATCHED")
	})
	t.Run("case-sensitive-names", func(t *testing.T) {
		cs := t.TempDir()
		writeTree(t, cs, map[string]string{"A.cs": "upper", "a.cs": "lower", "p/x.csproj": `<Project><ItemGroup><Compile Include="..\A.cs" /><Compile Include="..\B.CS" /></ItemGroup></Project>`, "b.cs": "b"})
		if entries, _ := os.ReadDir(cs); len(entries) != 4 {
			t.Skip("case-insensitive filesystem")
		}
		res, err := Corpus(testCtx(t), CorpusRequest{Root: cs, Limits: DefaultCorpusLimits(), Encoding: EncodingPolicy{Files: []FileEncoding{{"A.cs", "utf-8"}}}})
		if err != nil {
			t.Fatal(err)
		}
		for _, r := range res.Records {
			if r.Path == "A.cs" && (r.Encoding.Source != SourceDeclaration || len(r.DeclaredBy) != 1) {
				t.Fatalf("exact record: %+v", r)
			}
			if r.Path == "a.cs" && (r.Encoding.Source == SourceDeclaration || len(r.DeclaredBy) != 0) {
				t.Fatalf("other-case record: %+v", r)
			}
			if r.Path == "b.cs" && len(r.DeclaredBy) != 1 {
				t.Fatalf("single case-insensitive match: %+v", r)
			}
		}
	})
	t.Run("hardlink-is-record-scoped", func(t *testing.T) {
		hl := t.TempDir()
		writeTree(t, hl, map[string]string{"a.cs": "x", "b.cs": "y"})
		if err := os.Link(filepath.Join(hl, "a.cs"), filepath.Join(t.TempDir(), "alias.cs")); err != nil {
			t.Skipf("hard link unavailable: %v", err)
		}
		res, err := corpusRun(t, hl, DefaultCorpusLimits())
		if err != nil || res.Records[0].State != RecordUnsupported || res.Records[1].State != RecordCompleted || !hasCode(res.Findings, "HARDLINK_REJECTED") {
			t.Fatalf("hard link record: %v %+v", err, res.Records)
		}
	})
	t.Run("invalid", func(t *testing.T) {
		_, err := corpusRun(t, root, CorpusLimits{})
		kindOf(t, err, KindInvalidInput, "LIMITS_INVALID")
		_, err = Corpus(testCtx(t), CorpusRequest{Root: root, Limits: at, Encoding: EncodingPolicy{Files: []FileEncoding{{"nope.cs", "utf-8"}}}})
		kindOf(t, err, KindInvalidInput, "DECLARATION_UNMATCHED")
	})
}

// wallExpiringAtOpen makes the kit wall expire (with the kit's own cause) when the walk opens
// its first file, so the WALL_LIMIT path is taken mid-work by construction, not by timer
// scheduling (#61). It returns a restore function.
func wallExpiringAtOpen(t *testing.T) func() {
	t.Helper()
	var expire context.CancelCauseFunc
	testHookWall = func() (context.Context, context.CancelFunc) {
		ctx, c := context.WithCancelCause(context.Background())
		expire = c
		return ctx, func() { c(context.Canceled) }
	}
	testHookOpen = func(string) {
		if expire != nil {
			expire(errWall)
		}
	}
	return func() { testHookWall, testHookOpen = nil, nil }
}
