package kit

import (
	"bytes"
	"context"
	"encoding/xml"
	"io"
	"io/fs"
	"maps"
	"path"
	"slices"
	"strings"
	"time"
)

// Corpus record states, N461 roles and size classes (docs/specs/identity-and-evidence.md).
const (
	CorpusOperation = "private-corpus-local"

	RecordCompleted     = "COMPLETED"
	RecordResourceLimit = "RESOURCE_LIMIT"
	RecordUnsupported   = "UNSUPPORTED"
	RecordPresenceOnly  = "PRESENCE_ONLY"

	RoleUnclassified = "UNCLASSIFIED"
)

var (
	corpusExcluded   = []string{".git", ".hg", ".svn", ".vs", "bin", "obj", "packages", "testresults"}
	credentialExt    = map[string]bool{".pfx": true, ".p12": true, ".snk": true, ".key": true, ".pem": true, ".jks": true, ".keystore": true, ".pvk": true}
	vendorBinaryExt  = map[string]bool{".dll": true, ".exe": true, ".pdb": true}
	corpusRoutes     = map[string]string{".cs": "csharp", ".sql": "tsql", ".svc": "svc", ".config": "xml", ".resx": "xml", ".xsd": "xml", ".wsdl": "xml", ".xml": "xml", ".settings": "xml", ".datasource": "xml"}
	projectItemTypes = map[string]bool{"Compile": true, "Content": true, "None": true, "EmbeddedResource": true, "Page": true, "Resource": true,
		"ApplicationDefinition": true, "EntityDeploy": true, "ProjectReference": true}
	corpusMarkers = []string{"ServiceContract", "OperationContract", "ClientBase<", "System.Resources.ResourceManager", "InitializeComponent", "DevExpress.", "<auto-generated"}
)

// CorpusLimits are the private-corpus-local bounds; every field must be positive.
type CorpusLimits struct {
	Files, Records, FileBytes, TotalBytes, Depth, ReportBytes uint64
	Wall                                                      time.Duration
}

// DefaultCorpusLimits returns the registered private-corpus-local values for S01.
func DefaultCorpusLimits() CorpusLimits {
	return CorpusLimits{Files: 26000, Records: 26000, FileBytes: 33554432, TotalBytes: 3489660928, Depth: 32, ReportBytes: 67108864, Wall: 1800 * time.Second}
}

func (l CorpusLimits) valid() bool {
	return l.Files > 0 && l.Records > 0 && l.FileBytes > 0 && l.TotalBytes > 0 && l.Depth > 0 && l.ReportBytes > 0 && l.Wall > 0
}

// CorpusRequest inventories a caller-owned corpus root. Encoding.Profile is "cp949" for
// NET461-PHASE2-LOCAL-r1; per-file declarations come only from a user-provided manifest.
type CorpusRequest struct {
	Root     string
	Limits   CorpusLimits
	Encoding EncodingPolicy
	Profile  []byte // nil, or a strict tsgk-profile/r1 with encoding and narrower limits only
}

// CorpusRecord is one file. PRESENCE_ONLY records carry existence and size only.
type CorpusRecord struct {
	Path           string           `json:"path"`
	Role           string           `json:"role"`
	Route          string           `json:"route"`
	State          string           `json:"state"`
	Size           uint64           `json:"size"`
	SHA256         string           `json:"sha256,omitempty"`
	Encoding       *EncodingOutcome `json:"encoding,omitempty"`
	Newline        string           `json:"newline,omitempty"`
	SizeClass      string           `json:"size_class"`
	Generated      bool             `json:"generated"`
	GeneratedBasis string           `json:"generated_basis,omitempty"`
	DuplicateCount int              `json:"duplicate_count,omitempty"`
	DeclaredBy     []string         `json:"declared_by,omitempty"`
}

// ProjectItem is one declared .csproj item and its observation state.
type ProjectItem struct {
	Type     string `json:"type"`
	Include  string `json:"include"`
	Resolved string `json:"resolved,omitempty"`
	State    string `json:"state"` // MEMBER | NOT_FOUND | UNRESOLVED | EXCLUDED
}

// ProjectRecord is the declared membership observed in one .csproj (no MSBuild).
type ProjectRecord struct {
	Path         string        `json:"path"`
	State        string        `json:"state"` // PARSED | UNPARSED | NOT_READ
	Imports      int           `json:"imports"`
	IgnoredItems int           `json:"ignored_items"`
	Items        []ProjectItem `json:"items"`
}

// CorpusSummary carries counts and judgements only; it is the public projection.
type CorpusSummary struct {
	Files           int            `json:"files"`
	Records         int            `json:"records"`
	BytesRead       uint64         `json:"bytes_read"`
	ExcludedDirs    int            `json:"excluded_dirs"`
	States          map[string]int `json:"states"`
	PresenceOnly    map[string]int `json:"presence_only"`
	Roles           map[string]int `json:"roles"`
	Routes          map[string]int `json:"routes"`
	Encodings       map[string]int `json:"encodings"`
	EncodingCodes   map[string]int `json:"encoding_codes"`
	Newlines        map[string]int `json:"newlines"`
	SizeClasses     map[string]int `json:"size_classes"`
	Generated       int            `json:"generated"`
	DuplicateGroups int            `json:"duplicate_groups"`
	RedundantCopies int            `json:"redundant_copies"`
	Projects        map[string]int `json:"projects"`
	ProjectItems    map[string]int `json:"project_items"`
}

// CorpusResult is the private-corpus-local inventory. Records and Projects contain
// paths and stay in local untracked storage; Summary is the public projection.
type CorpusResult struct {
	Report
	Policy   Policy          `json:"policy"`
	Summary  CorpusSummary   `json:"summary"`
	Records  []CorpusRecord  `json:"records"`
	Projects []ProjectRecord `json:"projects"`
}

// Corpus inventories every non-excluded file under Root without executing anything.
// Credential-like files and vendor binaries are never opened. A file over FileBytes is a
// per-record RESOURCE_LIMIT; count, byte, record, depth, report and wall limits end the
// whole run RESOURCE_LIMIT with no partial PASS. pg-large-source-r1 never applies here.
func Corpus(ctx context.Context, req CorpusRequest) (CorpusResult, error) {
	l := req.Limits
	policy := corpusPolicy(l, req.Encoding)
	failWith := func(e *Error) (CorpusResult, error) {
		out := CorpusResult{Report: newReport("corpus"), Policy: policy, Records: []CorpusRecord{}, Projects: []ProjectRecord{}}
		failReport(&out.Report, e)
		return out, e
	}
	if !l.valid() {
		return failWith(fail(KindInvalidInput, "LIMITS_INVALID", "", nil))
	}
	var prof *profile
	if req.Profile != nil {
		var e *Error
		if prof, e = corpusProfile(&req); e != nil {
			return failWith(e)
		}
		l = req.Limits
		policy = corpusPolicy(l, req.Encoding)
	}
	declared, e := declarations(req.Encoding)
	if e != nil {
		return failWith(e)
	}
	r, e := startRun(ctx, l.Wall)
	if e != nil {
		return failWith(e)
	}
	defer r.cancel()
	osRoot, _, e := openRoot(req.Root)
	if e != nil {
		return failWith(e)
	}
	defer osRoot.Close()
	c := &corpus{r: r, g: newGuard(osRoot), limits: l, declared: declared, cp949: req.Encoding.Profile == "cp949", res: CorpusResult{Report: newReport("corpus"), Policy: policy}}
	if e := c.walk(); e != nil {
		return failWith(e)
	}
	for _, p := range slices.Sorted(maps.Keys(declared)) {
		if !c.exact[p] { // declarations match exact record paths
			return failWith(fail(KindInvalidInput, "DECLARATION_UNMATCHED", p, nil))
		}
	}
	if e := c.projects(); e != nil {
		return failWith(e)
	}
	c.finish()
	if prof != nil {
		c.res.Identities = append(c.res.Identities, prof.ref())
	}
	if e := sealOutput(c.res, l.ReportBytes); e != nil {
		return failWith(e)
	}
	return c.res, nil
}

func corpusPolicy(l CorpusLimits, enc EncodingPolicy) Policy {
	return Policy{Operation: CorpusOperation, Discovery: "bounded-inventory-r1", Files: l.Files, Records: l.Records, FileBytes: l.FileBytes, TotalBytes: l.TotalBytes,
		Depth: l.Depth, OutputBytes: l.ReportBytes, WallMillis: l.Wall.Milliseconds(), EncodingPolicy: encodingPolicyName(enc),
		Exclusions: append(append([]string{}, corpusExcluded...), "links-not-followed", "presence-only-credential-and-vendor-binary")}
}

// corpusProfile applies a profile to a corpus request. A corpus has no file selection;
// each profile limit must stay within both the caller's limits and the tracked
// private-corpus-local values, so a profile can never raise either.
func corpusProfile(req *CorpusRequest) (*profile, *Error) {
	prof, e := parseProfile(req.Profile)
	if e != nil {
		return nil, e
	}
	if prof.files != nil {
		return nil, fail(KindInvalidInput, "PROFILE_FILES_NOT_APPLICABLE", "profile#/files", nil)
	}
	if req.Encoding, e = prof.encodingFrom(req.Encoding); e != nil {
		return nil, e
	}
	l, t := req.Limits, DefaultCorpusLimits()
	got, e := prof.narrow(map[string]uint64{"files": min(l.Files, t.Files), "records": min(l.Records, t.Records), "file_bytes": min(l.FileBytes, t.FileBytes),
		"total_bytes": min(l.TotalBytes, t.TotalBytes), "depth": min(l.Depth, t.Depth), "output_bytes": min(l.ReportBytes, t.ReportBytes)})
	if e != nil {
		return nil, e
	}
	for k, dst := range map[string]*uint64{"files": &l.Files, "records": &l.Records, "file_bytes": &l.FileBytes, "total_bytes": &l.TotalBytes, "depth": &l.Depth, "output_bytes": &l.ReportBytes} {
		if _, set := prof.limits[k]; set {
			*dst = got[k]
		}
	}
	req.Limits = l
	return prof, nil
}

type corpus struct {
	r        *run
	g        *guard
	limits   CorpusLimits
	declared map[string]string
	cp949    bool
	res      CorpusResult
	index    map[string][]int // lower-case path -> record indexes (case-sensitive filesystems may hold several)
	exact    map[string]bool
	excluded int
	projSrc  map[string][]byte
}

func (c *corpus) walk() *Error {
	c.index = map[string][]int{}
	c.exact = map[string]bool{}
	c.projSrc = map[string][]byte{}
	c.res.Records = []CorpusRecord{}
	listed := uint64(0)
	stack := []string{"."}
	for len(stack) > 0 {
		dir := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		entries, e := c.g.readDir(c.r, dir, &listed, 2*c.limits.Files)
		if e != nil {
			return e
		}
		for i := len(entries) - 1; i >= 0; i-- {
			name := entries[i].Name()
			p := join(dir, name)
			info, e := c.g.lstat(p)
			if e != nil {
				return e
			}
			if info == nil {
				continue
			}
			if kind(info) == "dir" {
				if slices.Contains(corpusExcluded, strings.ToLower(name)) {
					c.excluded++
					continue
				}
				if depthOf(p) > c.limits.Depth {
					return fail(KindResourceLimit, "DEPTH_LIMIT", p, nil)
				}
				stack = append(stack, p)
				continue
			}
			if e := c.file(p, name, info); e != nil {
				return e
			}
		}
	}
	slices.SortFunc(c.res.Records, func(a, b CorpusRecord) int { return strings.Compare(a.Path, b.Path) })
	for i, rec := range c.res.Records {
		c.index[strings.ToLower(rec.Path)] = append(c.index[strings.ToLower(rec.Path)], i)
		c.exact[rec.Path] = true
	}
	return nil
}

func (c *corpus) file(p, name string, fi fs.FileInfo) *Error {
	n := uint64(len(c.res.Records) + 1)
	if n > c.limits.Files {
		return fail(KindResourceLimit, "FILE_COUNT_LIMIT", "", nil)
	}
	if n > c.limits.Records {
		return fail(KindResourceLimit, "RECORD_LIMIT", "", nil)
	}
	if depthOf(p) > c.limits.Depth {
		return fail(KindResourceLimit, "DEPTH_LIMIT", p, nil)
	}
	lower := strings.ToLower(name)
	ext := path.Ext(lower)
	rec := CorpusRecord{Path: p, Role: RoleUnclassified, Route: corpusRoutes[ext], Size: uint64(fi.Size())}
	rec.SizeClass = sizeClass(rec.Size)
	markers := map[string]bool{}
	switch {
	case !portable(p, false):
		rec.State = RecordUnsupported
		c.res.Findings = append(c.res.Findings, Finding{Code: "NONPORTABLE_PATH", Severity: "error", Path: p, Message: "portable path 규칙을 벗어난 이름은 읽지 않는다"})
	case kind(fi) != "file":
		rec.State = RecordUnsupported
		c.res.Findings = append(c.res.Findings, Finding{Code: "LINK_NOT_FOLLOWED", Severity: "error", Path: p, Message: "link·reparse point·special 항목은 따라가거나 읽지 않는다"})
	case credentialExt[ext] || vendorBinaryExt[ext]:
		rec.State = RecordPresenceOnly // existence and size only; never opened
	case rec.Size > c.limits.FileBytes:
		rec.State = RecordResourceLimit // not read
	default:
		nl := &newlineSink{}
		ms := &markerSink{found: markers}
		keep := uint64(0)
		if ext == ".csproj" {
			keep = c.limits.FileBytes
		}
		st, e := c.g.readFile(c.r, p, fi, c.limits.FileBytes, c.limits.TotalBytes, keep, nl, ms)
		if e != nil && e.Code == "HARDLINK_REJECTED" {
			rec.State = RecordUnsupported
			c.res.Findings = append(c.res.Findings, Finding{Code: "HARDLINK_REJECTED", Severity: "error", Path: p, Message: "hard link 파일은 읽지 않는다"})
			break
		}
		if e != nil {
			return e
		}
		rec.State, rec.SHA256 = RecordCompleted, st.sha256
		outcome := st.encoding.result(c.cp949, c.declared[p])
		rec.Encoding = &outcome
		rec.Newline = nl.class()
		if outcome.Code == "UTF32_BOM" || outcome.Code == "NUL_WITHOUT_BOM" {
			rec.Newline = "UNKNOWN"
		}
		if keep > 0 {
			c.projSrc[p] = st.content
		}
	}
	rec.Role = n461Role(lower, ext, markers)
	switch {
	case strings.HasSuffix(lower, ".designer.cs") || lower == "reference.cs":
		rec.Generated, rec.GeneratedBasis = true, "NAME"
	case markers["<auto-generated"]:
		rec.Generated, rec.GeneratedBasis = true, "MARKER"
	}
	c.res.Records = append(c.res.Records, rec)
	return nil
}

// n461Role assigns exactly one role; the first matching rule wins.
func n461Role(name, ext string, m map[string]bool) string {
	switch {
	case ext == ".svc":
		return "N461-SVC"
	case ext == ".config" || ext == ".wsdl" || ext == ".xsd":
		return "N461-XML"
	case ext == ".resx":
		return "N461-RESOURCE"
	case ext != ".cs":
		return RoleUnclassified
	case strings.HasSuffix(name, ".svc.cs") || name == "reference.cs" || m["ServiceContract"] || m["OperationContract"] || m["ClientBase<"]:
		return "N461-WCF-CS"
	case strings.HasSuffix(name, ".designer.cs") && m["System.Resources.ResourceManager"]:
		return "N461-RESOURCE"
	case strings.HasSuffix(name, ".designer.cs") || m["InitializeComponent"]:
		return "N461-FORM"
	case m["DevExpress."]:
		return "N461-DX202"
	}
	return RoleUnclassified
}

func sizeClass(n uint64) string {
	switch {
	case n <= 65536:
		return "LE_64KIB"
	case n <= 1048576:
		return "LE_1MIB"
	case n <= 4194304:
		return "LE_4MIB"
	case n <= 16777216:
		return "LE_16MIB"
	case n <= 33554432:
		return "LE_32MIB"
	}
	return "OVER_32MIB"
}

// projects observes declared .csproj membership: %xx decode, '\' -> '/', lexical '..'
// from the project directory, then a case-insensitive lookup; nothing is read again.
func (c *corpus) projects() *Error {
	c.res.Projects = []ProjectRecord{}
	for _, rec := range c.res.Records {
		if path.Ext(strings.ToLower(rec.Path)) != ".csproj" {
			continue
		}
		if e := c.r.check(); e != nil {
			return e
		}
		pr := ProjectRecord{Path: rec.Path, State: "NOT_READ", Items: []ProjectItem{}}
		src, ok := c.projSrc[rec.Path]
		if ok {
			items, imports, ignored, parsed := parseProject(src)
			pr.Imports, pr.IgnoredItems = imports, ignored
			pr.State = "UNPARSED"
			if parsed {
				pr.State = "PARSED"
				for _, it := range items {
					pr.Items = append(pr.Items, c.resolveItem(rec.Path, it))
				}
			}
		}
		c.res.Projects = append(c.res.Projects, pr)
	}
	return nil
}

type rawItem struct {
	typ, include string
	conditional  bool
}

func parseProject(src []byte) (items []rawItem, imports, ignored int, ok bool) {
	d := xml.NewDecoder(bytes.NewReader(bytes.TrimPrefix(src, []byte("\xEF\xBB\xBF"))))
	d.Strict = true
	d.CharsetReader = func(label string, in io.Reader) (io.Reader, error) {
		if strings.EqualFold(label, "utf-8") || strings.EqualFold(label, "us-ascii") {
			return in, nil
		}
		return nil, io.ErrUnexpectedEOF
	}
	type frame struct {
		name string
		cond bool
	}
	var stack []frame
	for {
		tok, err := d.Token()
		if err == io.EOF {
			return items, imports, ignored, len(stack) == 0
		}
		if err != nil {
			return nil, 0, 0, false
		}
		switch t := tok.(type) {
		case xml.StartElement:
			cond, include, hasInclude := false, "", false
			for _, a := range t.Attr {
				switch a.Name.Local {
				case "Condition":
					cond = true
				case "Include":
					include, hasInclude = a.Value, true
				case "Exclude":
					cond = true // exclusion needs evaluation; the declared items stay UNRESOLVED
				}
			}
			// Choose/When/Otherwise branches and Target-scoped item groups are not static declarations.
			if t.Name.Local == "Choose" || t.Name.Local == "Target" {
				cond = true
			}
			parentCond := len(stack) > 0 && stack[len(stack)-1].cond
			if t.Name.Local == "Import" {
				imports++
			}
			if hasInclude && len(stack) > 0 && stack[len(stack)-1].name == "ItemGroup" {
				if !projectItemTypes[t.Name.Local] {
					ignored++
				} else {
					for _, part := range strings.Split(include, ";") {
						if part = strings.TrimSpace(part); part != "" {
							items = append(items, rawItem{typ: t.Name.Local, include: part, conditional: cond || parentCond})
						}
					}
				}
			}
			stack = append(stack, frame{name: t.Name.Local, cond: cond || parentCond})
		case xml.EndElement:
			if len(stack) == 0 {
				return nil, 0, 0, false
			}
			stack = stack[:len(stack)-1]
		}
	}
}

func (c *corpus) resolveItem(project string, it rawItem) ProjectItem {
	out := ProjectItem{Type: it.typ, Include: it.include}
	if it.conditional || strings.Contains(it.include, "$(") || strings.Contains(it.include, "@(") || strings.Contains(it.include, "%(") {
		out.State = "UNRESOLVED"
		return out
	}
	decoded := percentDecode(it.include)
	if strings.ContainsAny(decoded, "*?") {
		out.State = "UNRESOLVED"
		return out
	}
	s := strings.ReplaceAll(decoded, `\`, "/")
	if strings.Contains(s, ":") || strings.HasPrefix(s, "/") {
		out.State = "NOT_FOUND" // drive, UNC or absolute form: outside the corpus root
		return out
	}
	joined := path.Clean(path.Join(path.Dir(project), s))
	if joined == ".." || strings.HasPrefix(joined, "../") || joined == "." {
		out.State = "NOT_FOUND"
		return out
	}
	out.Resolved = joined
	// Exact match first; otherwise one case-insensitive match (Windows rules). Several
	// case-insensitive candidates without an exact match are ambiguous.
	matches := c.index[strings.ToLower(joined)]
	pick := -1
	for _, i := range matches {
		if c.res.Records[i].Path == joined {
			pick = i
		}
	}
	if pick < 0 && len(matches) == 1 {
		pick = matches[0]
	}
	if pick < 0 && len(matches) > 1 {
		out.State = "UNRESOLVED"
		return out
	}
	if pick >= 0 {
		out.State = "MEMBER"
		rec := &c.res.Records[pick]
		if !slices.Contains(rec.DeclaredBy, project) {
			rec.DeclaredBy = append(rec.DeclaredBy, project)
		}
		return out
	}
	for _, seg := range strings.Split(strings.ToLower(joined), "/") {
		if slices.Contains(corpusExcluded, seg) {
			out.State = "EXCLUDED"
			return out
		}
	}
	out.State = "NOT_FOUND"
	return out
}

func percentDecode(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '%' && i+2 < len(s) && isHex(s[i+1]) && isHex(s[i+2]) {
			b.WriteByte(unhex(s[i+1])<<4 | unhex(s[i+2]))
			i += 2
			continue
		}
		b.WriteByte(s[i])
	}
	return b.String()
}

func isHex(b byte) bool { return '0' <= b && b <= '9' || 'a' <= b && b <= 'f' || 'A' <= b && b <= 'F' }

func unhex(b byte) byte {
	switch {
	case b <= '9':
		return b - '0'
	case b <= 'F':
		return b - 'A' + 10
	}
	return b - 'a' + 10
}

func (c *corpus) finish() {
	s := CorpusSummary{ExcludedDirs: c.excluded, States: map[string]int{}, PresenceOnly: map[string]int{}, Roles: map[string]int{}, Routes: map[string]int{},
		Encodings: map[string]int{}, EncodingCodes: map[string]int{}, Newlines: map[string]int{}, SizeClasses: map[string]int{}, Projects: map[string]int{}, ProjectItems: map[string]int{}}
	groups := map[string][]int{}
	for i, rec := range c.res.Records {
		if rec.SHA256 != "" {
			groups[rec.SHA256] = append(groups[rec.SHA256], i)
		}
	}
	for _, g := range groups {
		if len(g) > 1 {
			s.DuplicateGroups++
			s.RedundantCopies += len(g) - 1
			for _, i := range g {
				c.res.Records[i].DuplicateCount = len(g)
			}
		}
	}
	for _, rec := range c.res.Records {
		s.Files++
		s.Records++
		s.States[rec.State]++
		if rec.State == RecordPresenceOnly {
			kind := "vendor_binary"
			if credentialExt[path.Ext(strings.ToLower(rec.Path))] {
				kind = "credential"
			}
			s.PresenceOnly[kind]++
		}
		s.Roles[rec.Role]++
		route := rec.Route
		if route == "" {
			route = "UNROUTED"
		}
		s.Routes[route]++
		if rec.Encoding != nil {
			s.Encodings[rec.Encoding.Assessment+":"+rec.Encoding.Encoding+":"+rec.Encoding.Source]++
			if rec.Encoding.Code != "" {
				s.EncodingCodes[rec.Encoding.Code]++
			}
		}
		if rec.Newline != "" {
			s.Newlines[rec.Newline]++
		}
		s.SizeClasses[rec.SizeClass]++
		if rec.Generated {
			s.Generated++
		}
	}
	for _, p := range c.res.Projects {
		s.Projects[p.State]++
		for _, it := range p.Items {
			s.ProjectItems[it.State]++
		}
	}
	s.BytesRead = c.r.totalRead
	c.res.Summary = s
	c.res.Identities = append(c.res.Identities, c.res.Policy.ref())
	c.res.Coverage = Coverage{Requested: []string{"csproj-membership", "duplicates", "encoding-steps-1-6", "generated-marker", "newline", "role", "size-class"},
		Observed: []string{"csproj-membership", "duplicates", "encoding-steps-1-6", "generated-marker", "newline", "role", "size-class"}, Unsupported: []string{}}
	if s.EncodingCodes["ENCODING_TABLE_REQUIRED"] > 0 {
		c.res.Coverage.Unsupported = append(c.res.Coverage.Unsupported, "cp949-table")
	}
}

// newlineSink classifies line endings; UTF-16 input (by BOM) is read as code units.
type newlineSink struct {
	pending      []byte
	prevCR       bool
	crlf, lf, cr int
	head         []byte
	unit16, isBE bool
	decided      bool
}

func (n *newlineSink) Write(p []byte) (int, error) {
	if !n.decided {
		n.head = append(n.head, p...)
		if len(n.head) < 4 {
			return len(p), nil
		}
		n.decide()
		buf := n.head
		n.head = nil
		n.feed(buf)
		return len(p), nil
	}
	n.feed(p)
	return len(p), nil
}

func (n *newlineSink) decide() {
	n.decided = true
	h := n.head
	if len(h) >= 2 && !(len(h) >= 4 && h[0] == 0xFF && h[1] == 0xFE && h[2] == 0 && h[3] == 0) {
		if h[0] == 0xFF && h[1] == 0xFE {
			n.unit16 = true
		} else if h[0] == 0xFE && h[1] == 0xFF {
			n.unit16, n.isBE = true, true
		}
	}
}

func (n *newlineSink) feed(p []byte) {
	if !n.unit16 {
		for _, b := range p {
			n.unit(uint16(b))
		}
		return
	}
	buf := append(n.pending, p...)
	n.pending = nil
	for len(buf) >= 2 {
		u := uint16(buf[0]) | uint16(buf[1])<<8
		if n.isBE {
			u = uint16(buf[0])<<8 | uint16(buf[1])
		}
		n.unit(u)
		buf = buf[2:]
	}
	n.pending = append(n.pending, buf...)
}

func (n *newlineSink) unit(u uint16) {
	switch u {
	case '\n':
		if n.prevCR {
			n.crlf++
		} else {
			n.lf++
		}
		n.prevCR = false
	default:
		if n.prevCR {
			n.cr++
		}
		n.prevCR = u == '\r'
	}
}

func (n *newlineSink) class() string {
	if !n.decided {
		n.decide()
		buf := n.head
		n.head = nil
		n.feed(buf)
	}
	if n.prevCR {
		n.cr++
		n.prevCR = false
	}
	kinds := 0
	out := "NONE"
	for _, k := range []struct {
		n    int
		name string
	}{{n.crlf, "CRLF"}, {n.lf, "LF"}, {n.cr, "CR"}} {
		if k.n > 0 {
			kinds++
			out = k.name
		}
	}
	if kinds > 1 {
		return "MIXED"
	}
	return out
}

// markerSink records which ASCII markers occur anywhere in the raw bytes.
type markerSink struct {
	found map[string]bool
	tail  []byte
}

func (m *markerSink) Write(p []byte) (int, error) {
	buf := append(m.tail, p...)
	for _, k := range corpusMarkers {
		if !m.found[k] && bytes.Contains(buf, []byte(k)) {
			m.found[k] = true
		}
	}
	keep := 31
	if len(buf) < keep {
		keep = len(buf)
	}
	m.tail = append([]byte(nil), buf[len(buf)-keep:]...)
	return len(p), nil
}
