/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 2
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_a = 1,
  anon_sym_y = 2,
  anon_sym_h = 3,
  anon_sym_n = 4,
  anon_sym_s = 5,
  anon_sym_q = 6,
  anon_sym_BANG = 7,
  anon_sym_x = 8,
  anon_sym_DOT = 9,
  sym__hidden_text = 10,
  sym_source_file = 11,
  sym__hidden = 12,
  sym__shadow = 13,
  sym_word = 14,
  aux_sym__hidden_content = 15,
  alias_sym_aliased_child = 16,
  anon_alias_sym_anon = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_a] = "a",
  [anon_sym_y] = "y",
  [anon_sym_h] = "h",
  [anon_sym_n] = "n",
  [anon_sym_s] = "s",
  [anon_sym_q] = "q",
  [anon_sym_BANG] = "!",
  [anon_sym_x] = "x",
  [anon_sym_DOT] = ".",
  [sym__hidden_text] = "_hidden_text",
  [sym_source_file] = "source_file",
  [sym__hidden] = "_hidden",
  [sym__shadow] = "_shadow",
  [sym_word] = "word",
  [aux_sym__hidden_content] = "_hidden_content",
  [alias_sym_aliased_child] = "aliased_child",
  [anon_alias_sym_anon] = "anon",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_a] = anon_sym_a,
  [anon_sym_y] = anon_sym_y,
  [anon_sym_h] = anon_sym_h,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_q] = anon_sym_q,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__hidden_text] = sym__hidden_text,
  [sym_source_file] = sym_source_file,
  [sym__hidden] = sym__hidden,
  [sym__shadow] = sym__shadow,
  [sym_word] = sym_word,
  [aux_sym__hidden_content] = aux_sym__hidden_content,
  [alias_sym_aliased_child] = alias_sym_aliased_child,
  [anon_alias_sym_anon] = anon_alias_sym_anon,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_a] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_y] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_h] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_q] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__hidden_text] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__hidden] = {
    .visible = false,
    .named = true,
  },
  [sym__shadow] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__hidden_content] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_aliased_child] = {
    .visible = true,
    .named = true,
  },
  [anon_alias_sym_anon] = {
    .visible = true,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 2},
  [5] = {.index = 3, .length = 1},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 2},
  [8] = {.index = 5, .length = 2},
  [9] = {.index = 5, .length = 2},
  [10] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1, .inherited = true},
  [1] =
    {field_name, 1, .inherited = true},
    {field_type, 1},
  [3] =
    {field_name, 0},
  [4] =
    {field_value, 0},
  [5] =
    {field_value, 1, .inherited = true},
    {field_value, 2},
  [7] =
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_aliased_child,
  },
  [3] = {
    [1] = anon_alias_sym_anon,
  },
  [7] = {
    [1] = alias_sym_aliased_child,
  },
  [9] = {
    [1] = anon_alias_sym_anon,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__hidden, 3,
    sym__hidden,
    alias_sym_aliased_child,
    anon_alias_sym_anon,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 11,
        '.', 13,
        'a', 5,
        'b', 14,
        'h', 7,
        'n', 8,
        'q', 10,
        's', 9,
        'x', 12,
        'y', 6,
      );
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == 'a' ||
          lookahead == 'b') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(4);
      if (lookahead == 'h') ADVANCE(7);
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead == 'q') ADVANCE(10);
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_a);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_a);
      if (lookahead == 'a' ||
          lookahead == 'b') ADVANCE(14);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_y);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_h);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_s);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_q);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__hidden_text);
      if (lookahead == 'a' ||
          lookahead == 'b') ADVANCE(14);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_a] = ACTIONS(1),
    [anon_sym_y] = ACTIONS(1),
    [anon_sym_h] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_q] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__hidden_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [anon_sym_a] = ACTIONS(3),
    [anon_sym_h] = ACTIONS(5),
    [anon_sym_n] = ACTIONS(7),
    [anon_sym_s] = ACTIONS(9),
    [anon_sym_q] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(13), 1,
      anon_sym_x,
    STATE(13), 1,
      sym_word,
    STATE(17), 1,
      sym__shadow,
  [10] = 3,
    ACTIONS(15), 1,
      anon_sym_BANG,
    ACTIONS(17), 1,
      sym__hidden_text,
    STATE(4), 1,
      aux_sym__hidden_content,
  [20] = 3,
    ACTIONS(19), 1,
      anon_sym_BANG,
    ACTIONS(21), 1,
      sym__hidden_text,
    STATE(4), 1,
      aux_sym__hidden_content,
  [30] = 2,
    ACTIONS(24), 1,
      anon_sym_x,
    STATE(10), 1,
      sym__hidden,
  [37] = 2,
    ACTIONS(24), 1,
      anon_sym_x,
    STATE(12), 1,
      sym__hidden,
  [44] = 2,
    ACTIONS(24), 1,
      anon_sym_x,
    STATE(9), 1,
      sym__hidden,
  [51] = 2,
    ACTIONS(26), 1,
      sym__hidden_text,
    STATE(3), 1,
      aux_sym__hidden_content,
  [58] = 2,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      anon_sym_y,
  [65] = 2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_y,
  [72] = 1,
    ACTIONS(36), 2,
      ts_builtin_sym_end,
      anon_sym_BANG,
  [77] = 2,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_y,
  [84] = 2,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      anon_sym_BANG,
  [91] = 1,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_y,
  [96] = 1,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
  [100] = 1,
    ACTIONS(50), 1,
      anon_sym_DOT,
  [104] = 1,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
  [108] = 1,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
  [112] = 1,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
  [116] = 1,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
  [120] = 1,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
  [124] = 1,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 10,
  [SMALL_STATE(4)] = 20,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 37,
  [SMALL_STATE(7)] = 44,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 58,
  [SMALL_STATE(10)] = 65,
  [SMALL_STATE(11)] = 72,
  [SMALL_STATE(12)] = 77,
  [SMALL_STATE(13)] = 84,
  [SMALL_STATE(14)] = 91,
  [SMALL_STATE(15)] = 96,
  [SMALL_STATE(16)] = 100,
  [SMALL_STATE(17)] = 104,
  [SMALL_STATE(18)] = 108,
  [SMALL_STATE(19)] = 112,
  [SMALL_STATE(20)] = 116,
  [SMALL_STATE(21)] = 120,
  [SMALL_STATE(22)] = 124,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hidden_content, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hidden_content, 2, 0, 0), SHIFT_REPEAT(4),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 2),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 3),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shadow, 1, 0, 5),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hidden, 2, 0, 6),
  [48] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 4),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 7),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 8),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 9),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__shadow, 2, 0, 5),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tsgk_runtime_fields(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tsgk_runtime_fields",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
